codex/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin, databrowse

from web.models import *
from web import views
from django.views.generic import  DetailView, ListView, RedirectView
from django.views.generic.edit import FormView

#from django.views.generic.simple import redirect_to

from web.feeds import LatestEntriesFeed
from django.conf import settings

#from taggit

import logging
databrowse.site.register(Character)
databrowse.site.register(CharacterRelationship)
databrowse.site.register(Creature)
databrowse.site.register(CreatureRelationship)
databrowse.site.register(Object)
databrowse.site.register(ObjectRelationship)
databrowse.site.register(Author)
databrowse.site.register(Location)
databrowse.site.register(Image)
databrowse.site.register(Language)
databrowse.site.register(Religion)
databrowse.site.register(Adventure)
databrowse.site.register(Chronicle)
databrowse.site.register(Rule)
#databrowse.site.register(Tags)
#databrowse.site.register(TaggableManager)

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'codex.views.home', name='home'),
    url(r'^encounter/', include('codex.encounter.encounterurls')),
    url(r'^api/', include('codex.api.apiurls')),
    #url(r'^mobile/', include('codex.mobile.mobileurls')),
    #url(r'^map/', include('codex.codexmap.codexmapurls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^scriptorium/', include(admin.site.urls)),
    (r'^rss/$', LatestEntriesFeed()),
    #(r'^db/(.*)', databrowse.site.root),
#    (r'^grappelli/', include('grappelli.urls')),

    (r'^character/all/$',views.CharacterListingView),
    (r'^character/(?P<slug>.+)/$',views.CharacterDetailView),
    (r'^character/$',views.CharacterSectionView),

    (r'^creature/all/$',views.CreatureListingView),
    (r'^creature/(?P<slug>.+)/$',views.CreatureDetailView),
    (r'^creature/$',views.CreatureSectionView),

    (r'^location/all/$',views.LocationListingView),
    (r'^location/(?P<slug>.+)/$',views.LocationDetailView),
    (r'^location/$',views.LocationSectionView),

    (r'^adventure/all/$',views.AdventureListingView),
    (r'^adventure/(?P<slug>.+)/$',views.AdventureDetailView),
    (r'^adventure/$',views.AdventureSectionView),

    (r'^chronicle/all/$',views.ChronicleListingView),
    (r'^chronicle/(?P<slug>.+)/$',views.ChronicleDetailView),
    (r'^chronicle/$',views.ChronicleSectionView),

    (r'^rule/all/$',views.RuleListingView),
    (r'^rule/(?P<slug>.+)/$',views.RuleDetailView),
    (r'^rule/$',views.RuleSectionView),

    (r'^spell/all/$',views.SpellListingView),
    (r'^spell/(?P<slug>.+)/$',views.SpellDetailView),
    (r'^spell/$',views.SpellSectionView),

    (r'^fanart/all/$',views.FanartListingView),
    (r'^fanart/(?P<slug>.+)/$',views.FanartDetailView),
    (r'^fanart/$',views.FanartSectionView),


    (r'^object/all/$',views.ObjectListingView),
    (r'^object/(?P<slug>.+)/$',views.ObjectDetailView),
    (r'^object/$',views.ObjectSectionView),

    (r'^search/all/$', RedirectView.as_view(url='/advancedsearch/')),
    (r'^search/None/None/$',RedirectView.as_view(url='/advancedsearch/')),

    (r'^search/$',views.SearchRedirectView),


#    (r'^search/(?P<searchfilter>all|object|character|creature|location|adventure|chronicle)/(?P<canonlvl>ALL|NEW|AP|APC|C)/(?P<searchterm>.*)/$',views.SimpleSearchView),
    (r'^search/(?P<searchfilter>all|object|character|creature|location|adventure|chronicle)/(?P<searchterm>.*)/$',views.SimpleSearchView),
    (r'^search/(?P<searchfilter>all|object|character|creature|location|adventure|chronicle)/$',views.SimpleSearchView),

    (r'^contact/$',views.ContactView),
    (r'^send_info/send_form$',views.SendFormView),
    (r'^send_info/send_adventure$',views.SendAdventureView),
    (r'^send_info/send_chronicle$',views.SendChronicleView),
    (r'^send_info/send_spell$',views.SendSpellView),
    (r'^send_info/send_success$',views.SendSuccess),
    (r'^send_info/$',views.SendinfoView),

#    (r'^search/',views.AdvancedSearchView),
    (r'^advancedsearch/$',views.AdvancedSearchView),
    (r'^resadvancedsearch/$',views.ResultsAdvancedSearchView),

    (r'^dicegen/$',views.DiceGeneratorView),


    (r'^$', views.IndexView),
    (r'^rss.xml$', LatestEntriesFeed()),

)

if settings.ENVIRONMENT=="DEVELFO":
    urlpatterns += patterns('',
        url(r'^css/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/diacritica/GIT/emcodex/codex/templates/web/css/",
        }),
        url(r'^ima/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/diacritica/GIT/emcodex/codex/templates/web/ima/",
        }),
        url(r'^js/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/diacritica/GIT/emcodex/codex/templates/web/js/",
        }),
        url(r'^rotativo/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/diacritica/GIT/emcodex/codex/templates/web/rotativo/",
        }),
        url(r'^media/img/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/diacritica/GIT/emcodex/codex/media/img/",
        }),
        url(r'^media/files/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/diacritica/GIT/emcodex/codex/media/files/",
        }),
   )
elif settings.ENVIRONMENT=="DEVELWEN":
    urlpatterns += patterns('',
        url(r'^css/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/elwen/cortex-elwen/git/Codex/codex/templates/web/css/",
        }),
        url(r'^ima/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/elwen/cortex-elwen/git/Codex/codex/templates/web/ima/",
        }),
        url(r'^js/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/elwen/cortex-elwen/git/Codex/codex/templates/web/js/",
        }),
        url(r'^rotativo/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/elwen/cortex-elwen/git/Codex/codex/templates/web/rotativo/",
        }),
        url(r'^media/img/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/elwen/cortex-elwen/git/Codex/codex/media/img/",
        }),
        url(r'^media/files/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/elwen/cortex-elwen/git/Codex/codex/media/files/",
        }),
   )

handler404 = 'codex.web.views.NotFoundView'
handler500 = 'codex.web.views.InternalErrorView'

codex/encounter/models.py
from django.db import models

# Create your models here.

codex/web/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from django.db import models
from django import forms

from django.utils.translation import ugettext_lazy as _
from taggit.managers import TaggableManager
from twitter import Api

from django.utils import simplejson

import modelschoices as mc

# Create your models here.

class MainEntity(models.Model):
    """
    Valid for the main classes such as Character, Location, Creature, etc.
    """

    name = models.CharField(max_length=100, blank=False, null=False,                            verbose_name=_('Full name'))
    description = models.TextField(blank=True, null=True, verbose_name=_('Description'))

    image = models.ManyToManyField('Image', blank=True, null=True,  related_name=_("%(class)s Image"))
    attachments = models.ManyToManyField('AttachFile', blank=True, null=True,  related_name=_("%(class)s attachments"))

    tags = TaggableManager(blank=True)
    slug = models.SlugField(blank=True, null=True, max_length=200, help_text="A short label, generally used in URLs. AUTOMATICALLY ADDED!")

    comments = models.TextField(blank=True, null=True, verbose_name=_('Comments'))
    author = models.ManyToManyField("Author", blank=True, null=True,  verbose_name=_("Entity's authorship"))
    canon_level = models.CharField(max_length=5, blank=True, null=True, choices=mc.CANON_LEVEL_CHOICES, verbose_name=_('Canon Level'))
    highlight = models.BooleanField(blank=True, verbose_name=_(u'Highlight'))
    send_tweet = models.BooleanField(blank=True, verbose_name=_('Tweet new entity'))

    creation_date = models.DateTimeField(null=True, verbose_name=_('Creation date'))
    last_updated = models.DateTimeField(null=True, verbose_name=_('Last updated'))

    deactivated = models.BooleanField(blank=True, verbose_name=_('Deactivated'))

    def save(self, *args, **kwargs):
        unique_slug(self, slug_source='name', slug_field='slug')
        #FIXME - Send tweet goes here
        super(MainEntity, self).save(*args, **kwargs) #FIXME

    def __unicode__(self):
        return unicode("{slug}: {name}".format(slug=self.slug, name=self.name))

    def get_absolute_url(self):
        return unicode("/{ctype}/{slug}".format(ctype=self.__class__.__name__.lower(),slug=self.slug))

    def searchText(self):
        return unicode("%s %s %s" % (self.name, self.description, self.comments))

    class Meta:
        # db_table = 'model_name'
        # # verbose_name = _('model_name')
        get_latest_by = 'last_updated'
        ordering = ['-last_updated','id']
        abstract = True

class AuxiliaryEntity(models.Model):
    """
    Valid for auxiliary classes such as Image, Language, Religion, etc.
    """

    name = models.CharField(max_length=100, blank=False, null=False,                            verbose_name=_('Full name'))
    description = models.TextField(blank=True, null=True, verbose_name=_('Description'))
    image = models.ManyToManyField('Image', blank=True, null=True,  related_name=_("%(class)s Image"))
    tags = TaggableManager(blank=True)
    comments = models.TextField(blank=True, null=True, verbose_name=_('Comments'))
    author = models.ManyToManyField("Author", blank=True, null=True,  verbose_name=_("Entity's authorship"))
    canon_level = models.CharField(max_length=5, blank=True, null=True, choices=mc.CANON_LEVEL_CHOICES, verbose_name=_('Canon Level'))

    deactivated = models.BooleanField(blank=True, verbose_name=_('Deactivated'))
    creation_date = models.DateTimeField(null=True, verbose_name=_('Creation date'))
    last_updated = models.DateTimeField(null=True, verbose_name=_('Last updated'))

    def __unicode__(self):
        return unicode("{id}: {name}".format(id=self.id, name=self.name))

    def get_absolute_url(self):
        return unicode("/{ctype}/{id}".format(ctype=self.__class__.__name__.lower(),id=self.id))

    class Meta:
        # db_table = 'model_name'
        # verbose_name = _('model_name')
        get_latest_by = 'last_updated'
        ordering = ['-last_updated','id']
        abstract = True

class ImageEntity(models.Model):

    name = models.CharField(max_length=100, blank=False, null=False,                            verbose_name=_('Full name'))
    description = models.TextField(blank=True, null=True, verbose_name=_('Description'))
    image = models.ImageField(upload_to='img/', blank=True, null=True,  verbose_name=_("Image field"))
    tags = TaggableManager(blank=True)
    comments = models.TextField(blank=True, null=True, verbose_name=_('Comments'))
    author = models.ManyToManyField("Author", blank=True, null=True,  verbose_name=_("Entity's authorship"))
    canon_level = models.CharField(max_length=5, blank=True, null=True, choices=mc.CANON_LEVEL_CHOICES, verbose_name=_('Canon Level'))

    deactivated = models.BooleanField(blank=True, verbose_name=_('Deactivated'))
    creation_date = models.DateTimeField(null=True, verbose_name=_('Creation date'))
    last_updated = models.DateTimeField(null=True, verbose_name=_('Last updated'))

    def __unicode__(self):
        return unicode("{id}: {name}".format(id=self.id, name=self.name))

    def get_absolute_url(self):
        return unicode("/{ctype}/{id}".format(ctype=self.__class__.__name__.lower(),id=self.id))

    class Meta:
        # db_table = 'model_name'
        # verbose_name = _('model_name')
        get_latest_by = 'last_updated'
        ordering = ['-last_updated','id']
        abstract = True


class RelationEntity(models.Model):

    comments = models.TextField(blank=True, null=True, verbose_name=_('Comments'))
    canon_level = models.CharField(max_length=5, blank=True, null=True, choices=mc.CANON_LEVEL_CHOICES, verbose_name=_('Canon Level'))
    deactivated = models.BooleanField(blank=True, verbose_name=_('Deactivated'))

    def __unicode__(self):
        return unicode("{id}".format(id=self.id))

    class Meta:
        # db_table = 'model_name'
        # verbose_name = _('model_name')
        get_latest_by = 'last_updated'
        ordering = ['-last_updated','id']
        abstract = True


# -------- ### --------- #

# -------- Self contained classes -------- #

class Author(models.Model):

    name = models.CharField(max_length='100', blank=False, null=False, verbose_name=_('Full name'))
    nickname =  models.CharField(max_length='100', blank=True, null=True, verbose_name=_('Nickname'))
    otherdata =  models.TextField(blank=True, null=True, verbose_name=_('Other data'))
    url =  models.URLField(blank=True, null=True,  max_length=200, verbose_name=_("Author's web page"))
    photo = models.ManyToManyField('Image', blank=True, null=True,  related_name=_("Author's photos"))
    slug = models.SlugField(blank=True,null=True,max_length=200,help_text="A short label, generally used in URLs. AUTOMATICALLY ADDED!")

    def __unicode__(self):
        return unicode("%s -%s-" % (self.name, self.nickname))

    class Meta:
        # db_table = 'model_name'
        verbose_name = _(u'Author')
        get_latest_by = 'order_name'
        ordering = ['-name']


# -------- Main classes -------- #

class Character(MainEntity):

    gender = models.CharField(max_length=2, blank=True, null=True,
        choices=mc.GENDER_CHOICES, verbose_name=_('Gender'))
    level = models.CharField(max_length=3, blank=True, null=True,
        choices=mc.LEVEL_CHOICES, verbose_name=_('Level'))
    age = models.CharField(max_length=10, blank=True, null=True,
        verbose_name=_('Age'))
    AC = models.CharField(max_length=100, blank=True, null=True,
        verbose_name=_('AC'))
    move = models.CharField(max_length=100, blank=True, null=True,
        verbose_name=_('Movement'))
    moral = models.CharField(max_length=2, blank=True, null=True,
        choices=mc.MORALE_CHOICES, verbose_name=_('Morale'))
    saveroll = models.CharField(max_length=20, blank=True, null=True, choices=mc.SAVE_CHOICES, verbose_name=_('Save roll'))
    hitpoints = models.CharField(max_length=100, blank=True, null=True, verbose_name=_('Hitpoints'))
    alignment = models.CharField(max_length=3, blank=True, null=True, choices=mc.ALIGN_CHOICES, verbose_name=_('Alignment'))
    quote = models.TextField(blank=True, null=True, verbose_name=_('Quote'))
    species = models.CharField(max_length=30, blank=True, null=True, choices=mc.SPECIES_CHOICES, verbose_name=_('Species'))
    profession = models.CharField(max_length=30, blank=True, null=True, choices=mc.PROFESSION_CHOICES, verbose_name=_('Profession'))
    startdate = models.SmallIntegerField(blank=True, null=True,verbose_name=_('First appearance'))
    enddate = models.SmallIntegerField(blank=True, null=True,verbose_name=_('Disappearance date'))

    strengthstat = models.SmallIntegerField(blank=True, null=True,verbose_name=_('Strength'))
    dexteritystat = models.SmallIntegerField(blank=True, null=True,verbose_name=_('Dexterity'))
    constitutionstat = models.SmallIntegerField(blank=True, null=True,verbose_name=_('Contitution'))
    intelligencestat = models.SmallIntegerField(blank=True, null=True,verbose_name=_('Intelligence'))
    wisdomstat = models.SmallIntegerField(blank=True, null=True,verbose_name=_('Wisdom'))
    charismastat = models.SmallIntegerField(blank=True, null=True,verbose_name=_('Charisma'))

    religion = models.ManyToManyField("Religion", blank=True, null=True, related_name=_("Character's Religions"))

    treasurevalue = models.CharField(max_length=100, blank=True, null=True, verbose_name=_("Character's Treasure value"))

    status = models.CharField(max_length=5, blank=True, null=True, choices=mc.CHAR_STATUS_CHOICES, verbose_name=_('Status'))

    weapons = models.TextField(blank=True, null=True, verbose_name=_('Attacks'))
    pncorpc = models.CharField(max_length=3, blank=True, null=True, choices=mc.PNJ_CHOICES, verbose_name=_('NPC/PC'))

    languages = models.ManyToManyField("Language", blank=True, null=True, related_name=_("Character's Known languages"))

codex/encounters/views.py
# -*- coding: utf-8 -*-
# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render_to_response, get_object_or_404
from django.forms.models import modelformset_factory
from codex.web.models import *

from django.core import validators
from django.http import HttpResponseRedirect
from codex.settings import MEDIA_URL,STATIC_URL
from decimal import *

from django.template import Context, Template, RequestContext

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def EncounterIndex(request):

    return HttpResponse("OK")

codex/templates/encounter/encounter_gen.html
{% extends "basebasic.html" %}
{% block title %}
    <title>Codex de la Marca del Este - Generador de Encuentros</title>
    {% endblock %}
        
        {% block content %}

        <div id="contenido" >
            <div id="contenido-listados" >          
            <div id="columna-der-listados">

                <div id="volver"><span><a href="/">Volver a inicio</a>&nbsp;&nbsp;-&nbsp;&nbsp;&nbsp;</span> <a href="/encounter">Encuentros<!-- nombre de la categoria si es un resultado de listado de categoria O  palabra "Busqueda" e incluir el H1 de Resultado de busqueda de "El termino que busco"--></a></div> 

                <div id="central">
                <form action="/encounter">   

                        <div id="generador-encuentros">
                            <p>Te presentamos el generador de encuentros de Aventuras en La Marca del Este. En su versión actual, tiene en cuenta las relaciones de liderazgo entre criaturas, permite introducir la suma de niveles de los AJs, un nivel de dificultad, el criterio de canon, tipo de terreno y el alineamiento aceptado para las criaturas del encuentro. Se trata de una herramienta perfecta para los Dungeon Masters que quieran introducir cierta sorpresa en las aventuras de sus jugadores. <!--A medio plazo, está previsto también un generador de tesoros.--></p>
                            <div style="clear: both">&nbsp;</div>

                                        <h2 class="titulo-formulario-avanzado" >            
                                            Suma nivel AJs: 
                                        </h2>

                                        <div class="formulario-avanzado-2-columnas">
                                        <input style="padding: 5px 5px; font-size:16px;width:110px;"
                                            {% if form.players_level %}
                                                value = {{form.players_level}}
                                            {% else %}
                                                 value = 10
                                            {% endif %}
                                            type="text" name="players_level" />
                                        </div>


                                        <h2 class="titulo-formulario-avanzado">         
                                        Dificultad:                     
                                        </h2>

                                        <div class="formulario-avanzado-2-columnas">
                                            <select  name="chosen_difficulty">
                                            <option value="0" {% if form.chosen_difficulty == '0' %}selected{% endif %}>Fácil</option>
                                            <option value="1" {% if form.chosen_difficulty == '1' %}selected{% endif %}>Normal</option>
                                            <option value="2" {% if form.chosen_difficulty == '2' %}selected{% endif %}>Difícil</option>
                                            <option value="3" {% if form.chosen_difficulty == '3' %}selected{% endif %}>Épico</option>
                                             </select> 
                                        </div>

                                        <div style="clear: both">&nbsp;</div>             

                                        <h2 class="titulo-formulario-avanzado">         
                                        Evaluación:                     
                                        </h2>

                                        <div class="formulario-avanzado-2-columnas">
                                            <select  name="canon">
                                              <option value="ALL" {% if form.canon == 'ALL' %}selected{% endif %}>Cualquiera</option>
                                              <option value="C" {% if form.canon == 'C' %}selected{% endif %}>Canon</option>
                                              <option value="AP" {% if form.canon == 'AP' %}selected{% endif %}>Apócrifo</option>
                                              <option value="APC" {% if form.canon == 'APC' %}selected{% endif %}>En Estudio</option>
                                              <option value="NEW" {% if form.canon == 'NEW' %}selected{% endif %}>Nuevo</option>
                                             </select> 
                                        </div>

                                        <h2 class="titulo-formulario-avanzado">         
                                        Alineamiento:                       
                                        </h2>

                                        <div class="formulario-avanzado-2-columnas">
                                            <select name="align">
                                              <option value="ALL" {% if form.align == 'ALL' %}selected{% endif %}>Todos</option>
                                              <option value="L" {% if form.align == 'L' %}selected{% endif %}>Legal</option>
                                              <option value="N" {% if form.align == 'N' %}selected{% endif %}>Neutral</option>
                                              <option value="C" {% if form.align == 'C' %}selected{% endif %}>Caótico</option>
                                             </select> 
                                        </div>

                                        <div style="clear: both">&nbsp;</div>  

                                        <h2 class="titulo-formulario-avanzado">
					  Tipo de terreno:       
                                        </h2>

                                        <div class="formulario-avanzado-2-columnas">
                                            <select name="setting">
                                              <option value="0">Todos</option>
                                              {% for setting in settings_list %}
                                              <option value="{{setting.id}}" {% ifequal setting.id form.setting %}selected{% endifequal %}>{{setting.name}}</option>
                                             {% endfor %}
                                             </select> 
                                        </div>



                                     <div style="clear: both">&nbsp;</div>
                    </div>  

                    <div style="clear: both; text-align: center; width:820px; ">
                        <input class="boton_buscar" type="submit" value="Generar encuentro" style="font-size: 22px;height: 38px;"/>
                    </div>                   

                    </form>                    


                    <div style="clear: both"><br/>&nbsp;</div>
                    </div><!-- fin central -->
                    </div><!-- fin columna-der-listados -->   

                    <div id="resultado-generador">

                       <div class="para-impresion">
                           <h1>Codex de la marca del Este</h1>
                          <a href="http://codexdelamarca.com">URL:</a>
                        </div>

                            <h2>Encuentro generado </h2>
                            
                            {% if numcreatures %}
                                {% if leader %}
                                <h3>{{ leader.name }} (líder)  [<a href="/creature/{{leader.slug}}">+ info</a>] </h3>
                                <p><b>DG</b>: {{leader.hitdice|default:"--"}} - <b>CA</b>: {{leader.AC|default:"--"}} - <b>TS</b>: {{leader.get_saveroll_display|default_if_none:"--"}} - <b>Mov</b>: {{leader.move|default:"--"}} - <b>Moral</b>: {{leader.get_moral_display|default_if_none:"--"}} - <b>Alineamiento</b>: {{leader.get_alignment_display|default_if_none:"--"}} - <b>Px</b>: {{leader.XPvalue|default_if_none:"--"}}  </p>  
                                    {% if leader.attacks %}             
                                    <p><b>Ataque</b>: {{leader.attacks|safe}}  </p> 
                                    {% endif %}
                                    <p>
                                    {{leader.description|safe|truncatewords:200}}
                                    </p>
                                {% endif %}
                                <h3>{{ encounter.name }}  [<a href="/creature/{{encounter.slug}}">+ info</a>] </h3>
                                <p><b>Número</b>: {{numcreatures}} </p>
                                <p><b>DG</b>: {{encounter.hitdice|default:"--"}} - <b>CA</b>: {{encounter.AC|default:"--"}} - <b>TS</b>: {{encounter.get_saveroll_display|default_if_none:"--"}} - <b>Mov</b>: {{encounter.move|default:"--"}} - <b>Moral</b>: {{encounter.get_moral_display|default_if_none:"--"}} - <b>Alineamiento</b>: {{encounter.get_alignment_display|default_if_none:"--"}} - <b>Px</b>: {{encounter.XPvalue|default_if_none:"--"}}  </p>  
                                    {% if encounter.attacks %}             
                                    <p><b>Ataque</b>: {{encounter.attacks|safe}}  </p> 
                                    {% endif %}
                                <p>
                                {{encounter.description|safe|truncatewords:200}}
                                </p>
				<h2>Tesoro</h2>
				{% if treasure %}
                    <p>El tesoro se divide por tipo de criatura del encuentro y se multiplica por un número que tiene en cuenta el número de criaturas de cada tipo y añadiendo además un factor aleatorio. El resultado es: <b>tesoro x factor</b>.</p>
                    <p>¡Esto es una sugerencia de tesoro para este encuentro!</p>
                    {% for result in treasure %}
                        <p>- {{result}}</p>
                    {% endfor %}
                    </ul>
				{% else %}
				<p>No hay tesoro en este encuentro, ¡tanto esfuerzo para nada!</p>
				{% endif %}
                            {% else %}
                            <p>No hay encuentro, los aventureros pueden vivir unas horas más.</p>
                            <p>...o revisa tus criterios de selección.</p>
                            {% endif %}
                            
<!--  Pendiente-->
<!--                          <h2> Tesoro </h2> 

                           <h3>Tesoro total: 4000 mo</h3>-->

                           <div style="clear: both; text-align: center;  ">
                        <input class="boton_buscar" type="submit" value="Imprimir" style="font-size: 22px;height: 38px;" onclick="window.print();"/><br><br>
                    </div>

                       </div>       

                

                  

            </div><!-- fin contenido-articulos -->

        </div><!-- fin contenido -->
        
        <div id="pie">
        <div id="validaciones"> 
        Aventuras de la Marca del este 2011 - Validación: <a
        href="http://validator.w3.org/check?uri=referer">XHTML</a> | <a
        href="http://jigsaw.w3.org/css-validator/validator?uri=http://codexdelamarca.com/css/estilo.css">CSS</a>
        <br/><br/>
        <span style="font-size: 10px"> Desarrollo y mantenimiento: Angela
        Rivera Campos @ghilbrae y Pablo Ruiz Múzquiz @diacritica     - Diseño: <a
        href="http://jagvalverde.com/">Jose Valverde</a></span>
        </div><!-- fin validaciones -->
        </div><!-- fin pie -->
        </div><!-- fin contenedor -->
        {% endblock %}  

        