codex/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin, databrowse

from web.models import *
from web import views
from django.views.generic import  DetailView, ListView, RedirectView
from django.views.generic.edit import FormView

#from django.views.generic.simple import redirect_to

from web.feeds import LatestEntriesFeed
from django.conf import settings

#from taggit

import logging
databrowse.site.register(Character)
databrowse.site.register(CharacterRelationship)
databrowse.site.register(Creature)
databrowse.site.register(CreatureRelationship)
databrowse.site.register(Object)
databrowse.site.register(ObjectRelationship)
databrowse.site.register(Author)
databrowse.site.register(Location)
databrowse.site.register(Image)
databrowse.site.register(Language)
databrowse.site.register(Religion)
databrowse.site.register(Adventure)
databrowse.site.register(Chronicle)
databrowse.site.register(Rule)
#databrowse.site.register(Tags)
#databrowse.site.register(TaggableManager)

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'codex.views.home', name='home'),
    url(r'^encounter/', include('codex.encounter.encounterurls')),
    url(r'^api/', include('codex.api.apiurls')),
    #url(r'^mobile/', include('codex.mobile.mobileurls')),
    #url(r'^map/', include('codex.codexmap.codexmapurls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^scriptorium/', include(admin.site.urls)),
    (r'^rss/$', LatestEntriesFeed()),
    #(r'^db/(.*)', databrowse.site.root),
#    (r'^grappelli/', include('grappelli.urls')),

    (r'^character/all/$',views.CharacterListingView),
    (r'^character/(?P<slug>.+)/$',views.CharacterDetailView),
    (r'^character/$',views.CharacterSectionView),

    (r'^creature/all/$',views.CreatureListingView),
    (r'^creature/(?P<slug>.+)/$',views.CreatureDetailView),
    (r'^creature/$',views.CreatureSectionView),

    (r'^location/all/$',views.LocationListingView),
    (r'^location/(?P<slug>.+)/$',views.LocationDetailView),
    (r'^location/$',views.LocationSectionView),

    (r'^adventure/all/$',views.AdventureListingView),
    (r'^adventure/(?P<slug>.+)/$',views.AdventureDetailView),
    (r'^adventure/$',views.AdventureSectionView),

    (r'^chronicle/all/$',views.ChronicleListingView),
    (r'^chronicle/(?P<slug>.+)/$',views.ChronicleDetailView),
    (r'^chronicle/$',views.ChronicleSectionView),

    (r'^rule/all/$',views.RuleListingView),
    (r'^rule/(?P<slug>.+)/$',views.RuleDetailView),
    (r'^rule/$',views.RuleSectionView),

    (r'^spell/all/$',views.SpellListingView),
    (r'^spell/(?P<slug>.+)/$',views.SpellDetailView),
    (r'^spell/$',views.SpellSectionView),

    (r'^fanart/all/$',views.FanartListingView),
    (r'^fanart/(?P<slug>.+)/$',views.FanartDetailView),
    (r'^fanart/$',views.FanartSectionView),


    (r'^object/all/$',views.ObjectListingView),
    (r'^object/(?P<slug>.+)/$',views.ObjectDetailView),
    (r'^object/$',views.ObjectSectionView),

    (r'^search/all/$', RedirectView.as_view(url='/advancedsearch/')),
    (r'^search/None/None/$',RedirectView.as_view(url='/advancedsearch/')),

    (r'^search/$',views.SearchRedirectView),


#    (r'^search/(?P<searchfilter>all|object|character|creature|location|adventure|chronicle)/(?P<canonlvl>ALL|NEW|AP|APC|C)/(?P<searchterm>.*)/$',views.SimpleSearchView),
    (r'^search/(?P<searchfilter>all|object|character|creature|location|adventure|chronicle)/(?P<searchterm>.*)/$',views.SimpleSearchView),
    (r'^search/(?P<searchfilter>all|object|character|creature|location|adventure|chronicle)/$',views.SimpleSearchView),

    (r'^contact/$',views.ContactView),
    (r'^send_info/send_form$',views.SendFormView),
    (r'^send_info/send_adventure$',views.SendAdventureView),
    (r'^send_info/send_chronicle$',views.SendChronicleView),
    (r'^send_info/send_spell$',views.SendSpellView),
    (r'^send_info/send_success$',views.SendSuccess),
    (r'^send_info/$',views.SendinfoView),

#    (r'^search/',views.AdvancedSearchView),
    (r'^advancedsearch/$',views.AdvancedSearchView),
    (r'^resadvancedsearch/$',views.ResultsAdvancedSearchView),

    (r'^dicegen/$',views.DiceGeneratorView),


    (r'^$', views.IndexView),
    (r'^rss.xml$', LatestEntriesFeed()),

)

if settings.ENVIRONMENT=="DEVELFO":
    urlpatterns += patterns('',
        url(r'^css/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/diacritica/GIT/emcodex/codex/templates/web/css/",
        }),
        url(r'^ima/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/diacritica/GIT/emcodex/codex/templates/web/ima/",
        }),
        url(r'^js/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/diacritica/GIT/emcodex/codex/templates/web/js/",
        }),
        url(r'^rotativo/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/diacritica/GIT/emcodex/codex/templates/web/rotativo/",
        }),
        url(r'^media/img/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/diacritica/GIT/emcodex/codex/media/img/",
        }),
        url(r'^media/files/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/diacritica/GIT/emcodex/codex/media/files/",
        }),
   )
elif settings.ENVIRONMENT=="DEVELWEN":
    urlpatterns += patterns('',
        url(r'^css/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/elwen/cortex-elwen/git/Codex/codex/templates/web/css/",
        }),
        url(r'^ima/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/elwen/cortex-elwen/git/Codex/codex/templates/web/ima/",
        }),
        url(r'^js/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/elwen/cortex-elwen/git/Codex/codex/templates/web/js/",
        }),
        url(r'^rotativo/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/elwen/cortex-elwen/git/Codex/codex/templates/web/rotativo/",
        }),
        url(r'^media/img/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/elwen/cortex-elwen/git/Codex/codex/media/img/",
        }),
        url(r'^media/files/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': "/home/elwen/cortex-elwen/git/Codex/codex/media/files/",
        }),
   )

handler404 = 'codex.web.views.NotFoundView'
handler500 = 'codex.web.views.InternalErrorView'

codex/web/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from django.db import models
from django import forms

from django.utils.translation import ugettext_lazy as _
from taggit.managers import TaggableManager
from twitter import Api

from django.utils import simplejson

import modelschoices as mc

# Create your models here.

class MainEntity(models.Model):
    """
    Valid for the main classes such as Character, Location, Creature, etc.
    """

    name = models.CharField(max_length=100, blank=False, null=False,                            verbose_name=_('Full name'))
    description = models.TextField(blank=True, null=True, verbose_name=_('Description'))

    image = models.ManyToManyField('Image', blank=True, null=True,  related_name=_("%(class)s Image"))
    attachments = models.ManyToManyField('AttachFile', blank=True, null=True,  related_name=_("%(class)s attachments"))

    tags = TaggableManager(blank=True)
    slug = models.SlugField(blank=True, null=True, max_length=200, help_text="A short label, generally used in URLs. AUTOMATICALLY ADDED!")

    comments = models.TextField(blank=True, null=True, verbose_name=_('Comments'))
    author = models.ManyToManyField("Author", blank=True, null=True,  verbose_name=_("Entity's authorship"))
    canon_level = models.CharField(max_length=5, blank=True, null=True, choices=mc.CANON_LEVEL_CHOICES, verbose_name=_('Canon Level'))
    highlight = models.BooleanField(blank=True, verbose_name=_(u'Highlight'))
    send_tweet = models.BooleanField(blank=True, verbose_name=_('Tweet new entity'))

    creation_date = models.DateTimeField(null=True, verbose_name=_('Creation date'))
    last_updated = models.DateTimeField(null=True, verbose_name=_('Last updated'))

    deactivated = models.BooleanField(blank=True, verbose_name=_('Deactivated'))

    def save(self, *args, **kwargs):
        unique_slug(self, slug_source='name', slug_field='slug')
        #FIXME - Send tweet goes here
        super(MainEntity, self).save(*args, **kwargs) #FIXME

    def __unicode__(self):
        return unicode("{slug}: {name}".format(slug=self.slug, name=self.name))

    def get_absolute_url(self):
        return unicode("/{ctype}/{slug}".format(ctype=self.__class__.__name__.lower(),slug=self.slug))

    def searchText(self):
        return unicode("%s %s %s" % (self.name, self.description, self.comments))

    class Meta:
        # db_table = 'model_name'
        # # verbose_name = _('model_name')
        get_latest_by = 'last_updated'
        ordering = ['-last_updated','id']
        abstract = True

class AuxiliaryEntity(models.Model):
    """
    Valid for auxiliary classes such as Image, Language, Religion, etc.
    """

    name = models.CharField(max_length=100, blank=False, null=False,                            verbose_name=_('Full name'))
    description = models.TextField(blank=True, null=True, verbose_name=_('Description'))
    image = models.ManyToManyField('Image', blank=True, null=True,  related_name=_("%(class)s Image"))
    tags = TaggableManager(blank=True)
    comments = models.TextField(blank=True, null=True, verbose_name=_('Comments'))
    author = models.ManyToManyField("Author", blank=True, null=True,  verbose_name=_("Entity's authorship"))
    canon_level = models.CharField(max_length=5, blank=True, null=True, choices=mc.CANON_LEVEL_CHOICES, verbose_name=_('Canon Level'))

    deactivated = models.BooleanField(blank=True, verbose_name=_('Deactivated'))
    creation_date = models.DateTimeField(null=True, verbose_name=_('Creation date'))
    last_updated = models.DateTimeField(null=True, verbose_name=_('Last updated'))

    def __unicode__(self):
        return unicode("{id}: {name}".format(id=self.id, name=self.name))

    def get_absolute_url(self):
        return unicode("/{ctype}/{id}".format(ctype=self.__class__.__name__.lower(),id=self.id))

    class Meta:
        # db_table = 'model_name'
        # verbose_name = _('model_name')
        get_latest_by = 'last_updated'
        ordering = ['-last_updated','id']
        abstract = True

class ImageEntity(models.Model):

    name = models.CharField(max_length=100, blank=False, null=False,                            verbose_name=_('Full name'))
    description = models.TextField(blank=True, null=True, verbose_name=_('Description'))
    image = models.ImageField(upload_to='img/', blank=True, null=True,  verbose_name=_("Image field"))
    tags = TaggableManager(blank=True)
    comments = models.TextField(blank=True, null=True, verbose_name=_('Comments'))
    author = models.ManyToManyField("Author", blank=True, null=True,  verbose_name=_("Entity's authorship"))
    canon_level = models.CharField(max_length=5, blank=True, null=True, choices=mc.CANON_LEVEL_CHOICES, verbose_name=_('Canon Level'))

    deactivated = models.BooleanField(blank=True, verbose_name=_('Deactivated'))
    creation_date = models.DateTimeField(null=True, verbose_name=_('Creation date'))
    last_updated = models.DateTimeField(null=True, verbose_name=_('Last updated'))

    def __unicode__(self):
        return unicode("{id}: {name}".format(id=self.id, name=self.name))

    def get_absolute_url(self):
        return unicode("/{ctype}/{id}".format(ctype=self.__class__.__name__.lower(),id=self.id))

    class Meta:
        # db_table = 'model_name'
        # verbose_name = _('model_name')
        get_latest_by = 'last_updated'
        ordering = ['-last_updated','id']
        abstract = True


class RelationEntity(models.Model):

    comments = models.TextField(blank=True, null=True, verbose_name=_('Comments'))
    canon_level = models.CharField(max_length=5, blank=True, null=True, choices=mc.CANON_LEVEL_CHOICES, verbose_name=_('Canon Level'))
    deactivated = models.BooleanField(blank=True, verbose_name=_('Deactivated'))

    def __unicode__(self):
        return unicode("{id}".format(id=self.id))

    class Meta:
        # db_table = 'model_name'
        # verbose_name = _('model_name')
        get_latest_by = 'last_updated'
        ordering = ['-last_updated','id']
        abstract = True


# -------- ### --------- #

# -------- Self contained classes -------- #

class Author(models.Model):

    name = models.CharField(max_length='100', blank=False, null=False, verbose_name=_('Full name'))
    nickname =  models.CharField(max_length='100', blank=True, null=True, verbose_name=_('Nickname'))
    otherdata =  models.TextField(blank=True, null=True, verbose_name=_('Other data'))
    url =  models.URLField(blank=True, null=True,  max_length=200, verbose_name=_("Author's web page"))
    photo = models.ManyToManyField('Image', blank=True, null=True,  related_name=_("Author's photos"))
    slug = models.SlugField(blank=True,null=True,max_length=200,help_text="A short label, generally used in URLs. AUTOMATICALLY ADDED!")

    def __unicode__(self):
        return unicode("%s -%s-" % (self.name, self.nickname))

    class Meta:
        # db_table = 'model_name'
        verbose_name = _(u'Author')
        get_latest_by = 'order_name'
        ordering = ['-name']


# -------- Main classes -------- #

class Character(MainEntity):

    gender = models.CharField(max_length=2, blank=True, null=True,
        choices=mc.GENDER_CHOICES, verbose_name=_('Gender'))
    level = models.CharField(max_length=3, blank=True, null=True,
        choices=mc.LEVEL_CHOICES, verbose_name=_('Level'))
    age = models.CharField(max_length=10, blank=True, null=True,
        verbose_name=_('Age'))
    AC = models.CharField(max_length=100, blank=True, null=True,
        verbose_name=_('AC'))
    move = models.CharField(max_length=100, blank=True, null=True,
        verbose_name=_('Movement'))
    moral = models.CharField(max_length=2, blank=True, null=True,
        choices=mc.MORALE_CHOICES, verbose_name=_('Morale'))
    saveroll = models.CharField(max_length=20, blank=True, null=True, choices=mc.SAVE_CHOICES, verbose_name=_('Save roll'))
    hitpoints = models.CharField(max_length=100, blank=True, null=True, verbose_name=_('Hitpoints'))
    alignment = models.CharField(max_length=3, blank=True, null=True, choices=mc.ALIGN_CHOICES, verbose_name=_('Alignment'))
    quote = models.TextField(blank=True, null=True, verbose_name=_('Quote'))
    species = models.CharField(max_length=30, blank=True, null=True, choices=mc.SPECIES_CHOICES, verbose_name=_('Species'))
    profession = models.CharField(max_length=30, blank=True, null=True, choices=mc.PROFESSION_CHOICES, verbose_name=_('Profession'))
    startdate = models.SmallIntegerField(blank=True, null=True,verbose_name=_('First appearance'))
    enddate = models.SmallIntegerField(blank=True, null=True,verbose_name=_('Disappearance date'))

    strengthstat = models.SmallIntegerField(blank=True, null=True,verbose_name=_('Strength'))
    dexteritystat = models.SmallIntegerField(blank=True, null=True,verbose_name=_('Dexterity'))
    constitutionstat = models.SmallIntegerField(blank=True, null=True,verbose_name=_('Contitution'))
    intelligencestat = models.SmallIntegerField(blank=True, null=True,verbose_name=_('Intelligence'))
    wisdomstat = models.SmallIntegerField(blank=True, null=True,verbose_name=_('Wisdom'))
    charismastat = models.SmallIntegerField(blank=True, null=True,verbose_name=_('Charisma'))

    religion = models.ManyToManyField("Religion", blank=True, null=True, related_name=_("Character's Religions"))

    treasurevalue = models.CharField(max_length=100, blank=True, null=True, verbose_name=_("Character's Treasure value"))

    status = models.CharField(max_length=5, blank=True, null=True, choices=mc.CHAR_STATUS_CHOICES, verbose_name=_('Status'))

    weapons = models.TextField(blank=True, null=True, verbose_name=_('Attacks'))
    pncorpc = models.CharField(max_length=3, blank=True, null=True, choices=mc.PNJ_CHOICES, verbose_name=_('NPC/PC'))

    languages = models.ManyToManyField("Language", blank=True, null=True, related_name=_("Character's Known languages"))

codex/templates/web/character_listing.html
{% extends "basebasic.html" %}
{% block title %}
<title>East Mark Codex - Characters</title>
{% endblock %}
{% block navigation %}
		<div id="cabecera">
			<div id="menu">
				<ul>
					<li><a href="/">The Codex</a></li>	
					<li><a href="/character" class="seleccion">Characters</a></li>
					<li><a href="/creature">Bestiary</a></li>	
					<li><a href="/location">Locations</a></li>
					<li><a href="/object">Objects</a></li>	
					<li><a href="/adventure">Adventures</a></li>	
					<li><a href="/chronicle">Chronicles</a></li>
					<li><a href="/spell" >Spells</a></li>
					<li><a href="/rule" >Rules</a></li>
					<li><a href="/fanart" >Fan Art</a></li>
					<li><a href="/send_info">Send entry</a></li>	
					<li><a href="/contact">Contact</a></li>
        		</ul>
			</div><!-- fin menu -->
			
			<div id="logo">
				<a href="/"><img src="/ima/codex-logo.jpg" alt="Adventures in the East Mark Codex." /></a>
			</div><!-- fin logo -->
			
			<div id="slogan">
				A compilation of the knowledge of the East Mark.
			</div><!-- fin logo -->
			

{% endblock %}

{% block content %}			
		

		<div id="contenido" >
			<div id="contenido-listados" >			
			<div id="columna-der-listados">
				
				<div id="volver"><span><a href="/">Home</a>&nbsp;&nbsp;-&nbsp;&nbsp;&nbsp;</span> <a href="/character">Characters<!-- nombre de la categoria si es un resultado de listado de categoria O  palabra "Busqueda" e incluir el H1 de Resultado de busqueda de "El termino que busco"--></a></div>
				
				<div id="central">
					<h1>Available characters</h1>
			
                {% for object in results %}
                    <!-- Resultado aventureros -->
					<h2>
						<img src="/ima/ico-portada-personaje.png" alt="personaje"/><a href="/character/{{object.slug}}">{{object.name}}</a>						
						<span>
							<br/>
							<b>Canon:</b> {{object.get_canon_level_display}} - Published at <a href="/character">Characters</a>. {{object.last_updated.date}}.
						</span>						
					</h2>
					
					<p class="detalles-listado">

						<b>Species:</b> {{object.get_species_display|default_if_none:"--"}} - <b>Level:</b> {{object.level|default_if_none:"--"}} - <b>Class:</b> {{object.get_profession_display|default_if_none:"--"}} - <b>Type:</b> {{object.get_pncorpc_display|default_if_none:"--"}} - <b>Alignment:</b> {{object.get_alignment_display|default_if_none:"--"}}
						<br/><b>Locations:</b>
                          {% if object.relatedlocation.all %}
    					  {% for rlocation in object.relatedlocation.all %}
    					   {% if forloop.first %}
    						<a href="/location/{{rlocation.slug}}">{{rlocation.name}}</a>
    						{% endif %}
    						{% if forloop.last and forloop.last != forloop.first %}
    						 y <a href="/location/{{rlocation.slug}}">{{rlocation.name}}</a>
    						{% endif %}
    						{% if not forloop.last and not forloop.first %}
    						, <a href="/location/{{rlocation.slug}}">{{rlocation.name}}</a>
    						{% endif %}
    					{% endfor %}
                        {% else %}
                            --
                        {% endif %}

					</p>

					<p>
						{{object.description|safe|truncatewords:100}}
					</p>
                {% endfor %}

					<div id="navegacion-resultados">
						
						<ul id="pagina">

                            {% if results.has_previous %}
							<li class="siguiente"> <a href="?page=1">« First</a></li>
                            <li class="siguiente"><a href="?page={{ results.previous_page_number }}">« Previous</a>   </li>
                            {% else %}
                            <li class="anterior-off">« First</a></li>
                            <li class="anterior-off">« Previous</li>
							{% endif %}

							<li class="activo">Page {{ results.number }} of {{ results.paginator.num_pages }}</li>

                             {% if results.has_next %}
							<li class="siguiente"> <a href="?page={{ results.next_page_number }}">Next »</a></li>

							<li class="siguiente"><a href="?page={{results.paginator.num_pages}}">Last »</a></li>
                            {% else %}
                            <li class="anterior-off">Next »</li>
                            <li class="anterior-off">Last »</li>
                            {% endif %}
						</ul>
						
							
					</div>
					
					
					
				</div><!-- fin central -->
			</div><!-- fin columna-der-listados -->			
			</div><!-- fin contenido-articulos -->
		</div><!-- fin contenido -->
		
{% endblock %}		

codex/templates/web/location_detail.html
{% extends "base.html" %}
{% block title %}
<title>East Mark Codex - Location - {{object.name}}</title>
{% endblock %}
{% block navigation %}
		<div id="cabecera">
			<div id="menu">
				<ul>
                                        <li><a href="/">The Codex</a></li>      
                                        <li><a href="/character" >Characters</a></li>
                                        <li><a href="/creature">Bestiary</a></li>       
                                        <li><a href="/location" class="seleccion">Locations</a></li>
                                        <li><a href="/object">Objects</a></li>  
                                        <li><a href="/adventure">Adventures</a></li>    
                                        <li><a href="/chronicle">Chronicles</a></li>
                                        <li><a href="/spell" >Spells</a></li>
                                        <li><a href="/rule" >Rules</a></li>
                                        <li><a href="/fanart" >Fan Art</a></li>
                                        <li><a href="/send_info">Send entry</a></li>    
                                        <li><a href="/contact">Contact</a></li>
        		</ul>
			</div><!-- fin menu -->
			
			<div id="logo">
				<a href="/"><img src="/ima/codex-logo.jpg" alt="Codex de las aventuras de la Marca del Este." /></a>
			</div><!-- fin logo -->
			
			<div id="slogan">
				A compilation of the knowledge of the East Mark.
			</div><!-- fin logo -->
			
		
{% endblock %}

{% block leftcontent %}
		<div id="contenido" >
			<div id="contenido-articulos" >
			<div id="columna-izq">
				<div id="volver"><span><a href="/">Home</a>&nbsp;&nbsp;-&nbsp;&nbsp;&nbsp;</span> <a href="/location">Location</a></div>
				
				<h1><img src="/ima/ico-portada-lugar.png" alt="lugar"/>{{object.name}}
                 {% if user.is_authenticated and user.is_staff %}
                <a href="/scriptorium/web/location/{{object.id}}">[edit]</a>
                {% endif %}


                </h1>

				<p><b>Location: {{object.location|safe}}</b></p>
                {% if object.description %}
				<p>{{object.description|safe}}</p>
                {% endif %}
			    {% if object.comments %}				
                <h2>Nota del autor:</h2>
                <p>{{object.comments|safe}}</p>		
				{% endif %}
				
				

			</div><!-- fin columna-izq -->
{% endblock %}
{% block rightcontent %}
                {% if object.image.all %}
				<div id="expo-ima">
					  {% for image in object.image.all %}
					    {% if forloop.first %}

					<div id="ima-grande">
						<a href="#"><img src="{{ MEDIA_URL }}{{image.image.name}}" alt="icono" height="230px" width="350px"/></a>
						
				</div>
					<!--
					<div id="ima-mini">
						<a href="#"><img src="ima/ico-portada-item.jpg" alt="icono" height="50px" width="75px"/></a>
						<a href="#"><img src="ima/ico-portada-item.jpg" alt="icono" height="50px" width="75px"/></a>
						<a href="#"><img src="ima/ico-portada-item.jpg" alt="icono" height="50px" width="75px"/></a>
						<a href="#"><img src="ima/ico-portada-item.jpg" alt="icono" height="50px" width="75px"/></a>
					</div>
					-->
				</div><!-- fin expo-ima -->
				
				<div id="firma-ima">
                    {% if image.author.all %}
					<b>Image Author(s)</b>:
                    {% for author in image.author.all%}
					   {% if forloop.first %}
                        <a href="{{author.url}}">{{author.name}}</a>
						{% endif %}
						{% if forloop.last and forloop.last != forloop.first %}
						 y <a href="{{author.url}}">{{author.name}}</a>
						{% endif %}
						{% if not forloop.last and not forloop.first %}
						, <a href="{{author.url}}">{{author.name}}</a>
						{% endif %}
					{% endfor %}
                    {% endif %}
				</div><!-- fin expo-ima -->
					{% endif %}




				{% endfor %}
				  {% endif %}
				<h2>More info:</h2>
				
				<div class="lista2columnas">
					<ul>
					 <li><b>Type:</b> {{object.get_loctype_display|default_if_none:"--"}}</li>
					  <li><b>First appearance:</b> {{object.startdate|default_if_none:"--"}}</li>

					    <li><b>Status:</b> {{object.get_status_display|default_if_none:"--"}}</li>
					 <li><b>Disappeared in:</b> {{object.enddate|default_if_none:"--"}}</li>
					<li><b>Population:</b> {{object.population|default_if_none:"--"}}</li>
					  <li><b>Alignment:</b> {{object.get_alignment_display|default_if_none:"--"}}</li>

					
					</ul>
				</div><!-- fin lista2columnas-->
			  {% if object.orderedchars|length > 0 %}
				<h2>Characters:</h2>
				<div class="lista2columnas">
					<ul>
					  {% for character in object.orderedchars %}
						<li><a href="/character/{{character.slug}}">{{character.name}}</a></li>
                      {% endfor %}
					</ul>
				</div><!-- fin lista2columnas-->
               {% endif %}

			    {% for relatedobject in object.relatedobject.all %}
					  {% if relatedobject.rarity != "C" %}
        				<h2>Objects:</h2>
        				<div class="lista2columnas">
        					<ul>
        						<li><a href="/object/{{relatedobject.slug}}">{{relatedobject.name}}</a></li>
        					</ul>
        				</div><!-- fin lista2columnas-->
					{% endif %}
					{% endfor %}
				

</div>
{% endblock %}		